env:
  node: true

extends: 'eslint:recommended'

parserOptions:
  ecmaVersion: 5

rules:

  # Style
  indent:             [ error, tab, { SwitchCase: 1 }]
  linebreak-style:    [ error, unix ]
  quotes:             [ error, single ]
  semi:               [ error, always ]
  camelcase:          [ error ]
  no-trailing-spaces: [ error ]

  # Additional rules (possible errors)
  no-console: [ error ]

  # Additional rules (best practices)
  curly:                        [ error, all ]
  eqeqeq:                       [ error, always ]
  no-alert:                     [ error ]
  no-eval:                      [ error ]
  no-extend-native:             [ error ]
  no-floating-decimal:          [ error ]
  no-implicit-coercion:         [ error ]
  no-implied-eval:              [ error ]
  no-invalid-this:              [ error ]
  no-labels:                    [ error ]
  no-lone-blocks:               [ error ]
  no-loop-func:                 [ error ]
  no-new:                       [ error ]
  no-new-func:                  [ error ]
  no-new-wrappers:              [ error ]
  no-octal-escape:              [ error ]
  no-return-assign:             [ error, always ]
  no-script-url:                [ error ]
  no-self-compare:              [ error ]
  no-throw-literal:             [ error ]
  no-unmodified-loop-condition: [ error ]
  no-unused-expressions:        [ error ]
  no-useless-concat:            [ error ]
  no-useless-return:            [ error ]
  no-warning-comments:          [ warn, { location: anywhere, terms: [ TODO ] }]
  prefer-regex-literals:        [ error ]

  # Additional rules (strict mode)
  strict: [ error, global ]

  # Additional rules (variables)
  no-shadow: [ error, { builtinGlobals: true }]

  # Relaxed rules
  no-redeclare:          [ off ]
  no-constant-condition: [ error, { checkLoops: false }]
