/*!
 * -------------------------------------------------------------------------- *
 *                                                                            *
 *    Kokopu - A JavaScript/TypeScript chess library.                         *
 *    <https://www.npmjs.com/package/kokopu>                                  *
 *    Copyright (C) 2018-2026  Yoann Le Montagner <yo35 -at- melix.net>       *
 *                                                                            *
 *    Kokopu is free software: you can redistribute it and/or                 *
 *    modify it under the terms of the GNU Lesser General Public License      *
 *    as published by the Free Software Foundation, either version 3 of       *
 *    the License, or (at your option) any later version.                     *
 *                                                                            *
 *    Kokopu is distributed in the hope that it will be useful,               *
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of          *
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the            *
 *    GNU Lesser General Public License for more details.                     *
 *                                                                            *
 *    You should have received a copy of the GNU Lesser General               *
 *    Public License along with this program. If not, see                     *
 *    <http://www.gnu.org/licenses/>.                                         *
 *                                                                            *
 * -------------------------------------------------------------------------- */


const { ZipArchive } = require('archiver');
const fs = require('fs');
const path = require('path');
const process = require('process');
const webpack = require('webpack');
const { author, license, version } = require('../package.json');

// Output file generated by this script.
const output = path.resolve(__dirname, `../dist/kokopu-${version}.zip`);

// Temporary files are generated in this directory.
const buildDir = path.resolve(__dirname, '../build');


const banner = `/*!
 * kokopu (https://www.npmjs.com/package/kokopu)
 * @version ${version}
 * @author ${author}
 * @license ${license}
 */`;


function runWebpack(mode, outputFilename) {

    const config = {
        mode,
        devtool: false,
        entry: path.resolve(__dirname, '../src/index.ts'),
        output: {
            path: buildDir,
            filename: outputFilename,
            library: { name: 'kokopu', type: 'umd' },
            globalObject: 'this',
        },
        plugins: [ new webpack.BannerPlugin({ banner, raw: true }) ],
        module: {
            rules: [
                {
                    test: /\.ts$/,
                    use: {
                        loader: 'ts-loader',
                        options: {
                            compilerOptions: {
                                declaration: false,
                            },
                        },
                    },
                    exclude: /node_modules/,
                },
            ],
        },
        resolve: {
            extensions: [ '.ts', '.js' ],
        },
    };

    // Run webpack with the current config and return a Promise.
    return new Promise((resolve, reject) => {
        webpack(config, (err, stats) => {
            if (err) { reject(err); }
            else if (stats.hasErrors()) { reject(new Error(stats.toString({ errors: true }))); }
            else { resolve(); }
        });
    });
}

// Merge all lib files into a single one, exporting the symbol `kokopu`.
async function buildUnminifiedLib() {
    await runWebpack('development', 'kokopu.js');
}

// Build the minified lib file.
async function buildMinifiedLib() {
    await runWebpack('production', 'kokopu.min.js');
}

// Create the archive.
async function buildArchive() {
    fs.mkdirSync(path.dirname(output), { recursive: true });
    const archive = new ZipArchive();
    archive.pipe(fs.createWriteStream(output));
    for (const file of [ 'README.md', 'CHANGELOG.md', 'LICENSE' ]) {
        archive.file(path.resolve(__dirname, '../' + file), { name: file });
    }
    for (const file of [ 'kokopu.js', 'kokopu.min.js', 'kokopu.min.js.LICENSE.txt' ]) {
        archive.file(path.resolve(buildDir, file), { name: file });
    }
    return archive.finalize();
}


async function run() {
    await buildUnminifiedLib();
    await buildMinifiedLib();
    await buildArchive();
}

run().catch(err => { console.error(err); process.exitCode = 1; });
